{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "nats-k8s-oidc-callout.fullname" . }}
  labels:
    {{- include "nats-k8s-oidc-callout.labels" . | nindent 4 }}
rules:
  # Need to list and watch ServiceAccounts cluster-wide for the informer
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get", "list", "watch"]
{{- end }}
