{{- if .Values.rbac.create -}}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "nats-k8s-oidc-callout.fullname" . }}
  labels:
    {{- include "nats-k8s-oidc-callout.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "nats-k8s-oidc-callout.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "nats-k8s-oidc-callout.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
