{{- if .Values.metrics.podMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "nats-k8s-oidc-callout.fullname" . }}
  {{- if .Values.metrics.podMonitor.namespace }}
  namespace: {{ .Values.metrics.podMonitor.namespace }}
  {{- end }}
  labels:
    {{- include "nats-k8s-oidc-callout.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.metrics.podMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "nats-k8s-oidc-callout.selectorLabels" . | nindent 6 }}
  podMetricsEndpoints:
  - port: http
    path: {{ .Values.metrics.podMonitor.path | default "/metrics" }}
    {{- with .Values.metrics.podMonitor.interval }}
    interval: {{ . }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.scrapeTimeout }}
    scrapeTimeout: {{ . }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.relabelings }}
    relabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
    {{- with .Values.metrics.podMonitor.metricRelabelings }}
    metricRelabelings:
      {{- toYaml . | nindent 6 }}
    {{- end }}
{{- end }}
