{{- with .Values.secretVolume }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-k8s-oidc-callout.fullname" $ }}-volume
  labels:
    {{- include "nats-k8s-oidc-callout.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value }}
  {{- end }}
{{- end }}
