{{- with .Values.secretEnv }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "nats-k8s-oidc-callout.fullname" $ }}-env
  labels:
    {{- include "nats-k8s-oidc-callout.labels" $ | nindent 4 }}
type: Opaque
data:
  {{- range $key, $value := . }}
  {{ $key }}: {{ $value | b64enc }}
  {{- end }}
{{- end }}
